export const ACTION_NOOP = 'ACTION_NOOP';

export const ACTION_SET_RUNTIME_VARIABLE = 'ACTION_SET_RUNTIME_VARIABLE';
export const ACTION_SET_RUNTIME_ERROR = 'ACTION_SET_RUNTIME_ERROR';
export const ACTION_SET_RUNTIME_ERROR_FULFILLED = 'ACTION_SET_RUNTIME_ERROR_FULFILLED';

export const ACTION_SET_LOCALE = 'ACTION_SET_LOCALE';

export const ACTION_PING = 'ACTION_PING';
export const ACTION_PONG = 'ACTION_PONG';

export const ACTION_SEND_HTTP_REQUEST = 'ACTION_SEND_HTTP_REQUEST';
export const ACTION_RECEIVE_HTTP_RESPONSES = 'ACTION_RECEIVE_HTTP_RESPONSES';
