export const DEFAULT_LOCALE = 'en';

export const ACTION_SET_RUNTIME_VARIABLE = 'ACTION_SET_RUNTIME_VARIABLE';
export const ACTION_SET_LOCALE = 'ACTION_SET_LOCALE';
export const ACTION_PING = 'ACTION_PING';
export const ACTION_PONG = 'ACTION_PONG';
